version: '3.3'
services:
  postgredb:
    container_name: postgres-vision
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: P0stgr35V1z10n
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default
